# Introduction Example

In [1]:
import tensorly as tl
import numpy as np

tl.set_backend('pytorch') # Or 'mxnet', 'numpy', 'tensorflow' or 'cupy'

# tensor of size 3x4x2
tensor = tl.tensor(np.arange(24).reshape((3, 4, 2)), device='cuda:0')
unfolded = tl.unfold(tensor, mode=0)
tl.fold(unfolded, mode=0, shape=tensor.shape)

tensor([[[ 0.,  1.],
         [ 2.,  3.],
         [ 4.,  5.],
         [ 6.,  7.]],

        [[ 8.,  9.],
         [10., 11.],
         [12., 13.],
         [14., 15.]],

        [[16., 17.],
         [18., 19.],
         [20., 21.],
         [22., 23.]]], device='cuda:0')

In [2]:
from tensorly.decomposition import tucker
# Apply Tucker decomposition
tucker_tensor = tucker(tensor, rank=[2, 2, 2])
# Reconstruct the full tensor from the decomposed form
tl.tucker_to_tensor(tucker_tensor)

tensor([[[-3.6955e-06,  1.0000e+00],
         [ 2.0000e+00,  3.0000e+00],
         [ 4.0000e+00,  5.0000e+00],
         [ 6.0000e+00,  7.0000e+00]],

        [[ 8.0000e+00,  9.0000e+00],
         [ 1.0000e+01,  1.1000e+01],
         [ 1.2000e+01,  1.3000e+01],
         [ 1.4000e+01,  1.5000e+01]],

        [[ 1.6000e+01,  1.7000e+01],
         [ 1.8000e+01,  1.9000e+01],
         [ 2.0000e+01,  2.1000e+01],
         [ 2.2000e+01,  2.3000e+01]]], device='cuda:0')

torch.Tensor

# CP decomposition

In [7]:
tensor = tl.tensor([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
                        [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
                        [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
                        [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
                        [ 0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
                        [ 0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
                        [ 0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
                        [ 0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
                        [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
                        [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
                        [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
                        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]], device='cuda:0')

tensor




tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0.],
        [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
        [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
        [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
        [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
        [0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], device='cuda:0')

In [11]:
tensor.shape

torch.Size([12, 12])

In [10]:
from tensorly.decomposition import parafac
factors = parafac(tensor, rank=2, verbose=2)
len(factors)

Starting iteration 1
Mode 0 of 2
Mode 1 of 2
reconstruction error=0.0003452669770922512
Starting iteration 2
Mode 0 of 2
Mode 1 of 2
iteration 1, reconstruction error: 0.0003452669770922512, decrease = 0.0, unnormalized = 0.0027621358167380095
PARAFAC converged after 1 iterations


2

In [9]:
factors.factors

[tensor([[ 0.0000,  0.0000],
         [ 1.6601,  1.1154],
         [ 1.6601,  1.1154],
         [ 1.6601,  1.1154],
         [ 3.0262, -0.9178],
         [ 3.0262, -0.9178],
         [ 3.0262, -0.9178],
         [ 3.0262, -0.9178],
         [ 1.6601,  1.1154],
         [ 1.6601,  1.1154],
         [ 1.6601,  1.1154],
         [ 0.0000,  0.0000]], device='cuda:0'),
 tensor([[ 0.0000,  0.0000],
         [ 0.2277, -0.3389],
         [ 0.2277, -0.3389],
         [ 0.2277, -0.3389],
         [ 0.4150,  0.2788],
         [ 0.4150,  0.2788],
         [ 0.4150,  0.2788],
         [ 0.4150,  0.2788],
         [ 0.2277, -0.3389],
         [ 0.2277, -0.3389],
         [ 0.2277, -0.3389],
         [ 0.0000,  0.0000]], device='cuda:0')]

In [6]:
# construct back to full tensor
tl.cp_to_tensor(factors)

tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00, -8.6824e-08, -8.6824e-08, -8.6824e-08,  1.0000e+00,
          1.0000e+00,  1.0000e+00,  1.0000e+00, -8.6824e-08, -8.6824e-08,
         -8.6824e-08,  0.0000e+00],
        [ 0.0000e+00, -8.6824e-08, -8.6824e-08, -8.6824e-08,  1.0000e+00,
          1.0000e+00,  1.0000e+00,  1.0000e+00, -8.6824e-08, -8.6824e-08,
         -8.6824e-08,  0.0000e+00],
        [ 0.0000e+00, -8.6824e-08, -8.6824e-08, -8.6824e-08,  1.0000e+00,
          1.0000e+00,  1.0000e+00,  1.0000e+00, -8.6824e-08, -8.6824e-08,
         -8.6824e-08,  0.0000e+00],
        [ 0.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00,
          1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00,
          1.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00,
      