In [1]:
import torch

In [2]:
# empty matrix
torch.empty(5,3)

tensor([[-2.7445e-33, -2.0127e-19,  1.4013e-45],
        [ 0.0000e+00,  1.4013e-45,  1.6751e-37],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 1.6751e-37, -1.6757e+38,  4.5887e-41],
        [-1.1575e-20,  1.6751e-37,  0.0000e+00]])

In [3]:
torch.rand(5,3)

tensor([[0.2336, 0.2674, 0.6401],
        [0.8528, 0.4248, 0.8306],
        [0.6787, 0.1553, 0.1650],
        [0.5629, 0.4210, 0.3223],
        [0.5001, 0.5963, 0.4119]])

In [4]:
torch.tensor([[2.2, 1.0],[ 0.2, 3.0]])

tensor([[2.2000, 1.0000],
        [0.2000, 3.0000]])

In [5]:
x = torch.rand(3,3)
y = torch.rand(3,3)

print(x)
print(y)
print("=====================================")

print(torch.add(x,y))
print(y.add(x))

tensor([[0.9985, 0.3267, 0.9495],
        [0.5645, 0.1429, 0.0695],
        [0.2516, 0.0397, 0.0391]])
tensor([[0.3312, 0.9406, 0.6410],
        [0.8410, 0.7808, 0.3270],
        [0.4759, 0.8584, 0.2059]])
tensor([[1.3297, 1.2673, 1.5904],
        [1.4055, 0.9237, 0.3965],
        [0.7275, 0.8981, 0.2450]])
tensor([[1.3297, 1.2673, 1.5904],
        [1.4055, 0.9237, 0.3965],
        [0.7275, 0.8981, 0.2450]])


In [6]:
x[:,2]

tensor([0.9495, 0.0695, 0.0391])

In [7]:
# reshape tensor
x.view(9,1)

tensor([[0.9985],
        [0.3267],
        [0.9495],
        [0.5645],
        [0.1429],
        [0.0695],
        [0.2516],
        [0.0397],
        [0.0391]])

In [8]:
# get value with .item()
x[2,1].item()

0.0396881103515625

In [9]:
# convert to numpy
x.numpy()

array([[0.99846184, 0.32674825, 0.94948655],
       [0.56450367, 0.14286959, 0.06953365],
       [0.25159055, 0.03968811, 0.03912282]], dtype=float32)

In [10]:
x.add(10)

tensor([[10.9985, 10.3267, 10.9495],
        [10.5645, 10.1429, 10.0695],
        [10.2516, 10.0397, 10.0391]])

In [11]:
import numpy as np
a = np.random.rand(1,5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)

print(a)
print(b)

[[1.70098768 1.90954209 1.44068534 1.20375881 1.03660735]]
tensor([[1.7010, 1.9095, 1.4407, 1.2038, 1.0366]], dtype=torch.float64)


In [12]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x+y
    
    print(z)
    print(z.to("cpu", torch.double))


tensor([[1.9985, 1.3267, 1.9495],
        [1.5645, 1.1429, 1.0695],
        [1.2516, 1.0397, 1.0391]], device='cuda:0')
tensor([[1.9985, 1.3267, 1.9495],
        [1.5645, 1.1429, 1.0695],
        [1.2516, 1.0397, 1.0391]], dtype=torch.float64)
