In [1]:
import torch

In [5]:
# empty matrix
torch.empty(5,3)

tensor([[-1.4025e+03,  3.0667e-41, -2.0777e-19],
        [ 4.5646e-41,  4.4842e-44,  0.0000e+00],
        [ 8.9683e-44,  0.0000e+00, -1.3961e+03],
        [ 3.0667e-41,  1.7853e-23,  4.5646e-41],
        [ 3.4871e+10, -6.0830e+15,  1.8561e-23]])

In [6]:
torch.rand(5,3)

tensor([[0.4914, 0.4167, 0.2991],
        [0.7824, 0.8328, 0.3486],
        [0.5981, 0.4514, 0.3977],
        [0.4712, 0.3939, 0.9073],
        [0.2050, 0.5062, 0.8150]])

In [8]:
torch.tensor([[2.2, 1.0],[ 0.2, 3.0]])

tensor([[2.2000, 1.0000],
        [0.2000, 3.0000]])

In [59]:
x = torch.rand(3,3)
y = torch.rand(3,3)

print(x)
print(y)
print("=====================================")

print(torch.add(x,y))
print(y.add(x))

tensor([[0.9990, 0.2840, 0.7426],
        [0.1356, 0.5449, 0.3475],
        [0.8112, 0.3039, 0.1372]])
tensor([[0.2583, 0.3886, 0.6903],
        [0.2567, 0.5371, 0.4416],
        [0.7761, 0.6734, 0.2688]])
tensor([[1.2573, 0.6726, 1.4329],
        [0.3923, 1.0820, 0.7891],
        [1.5872, 0.9773, 0.4061]])
tensor([[1.2573, 0.6726, 1.4329],
        [0.3923, 1.0820, 0.7891],
        [1.5872, 0.9773, 0.4061]])


In [60]:
x[:,2]

tensor([0.7426, 0.3475, 0.1372])

In [61]:
# reshape tensor
x.view(9,1)

tensor([[0.9990],
        [0.2840],
        [0.7426],
        [0.1356],
        [0.5449],
        [0.3475],
        [0.8112],
        [0.3039],
        [0.1372]])

In [62]:
# get value with .item()
x[2,1].item()

0.30386263132095337

In [63]:
# convert to numpy
x.numpy()

array([[0.9989867 , 0.2839948 , 0.74262834],
       [0.13563436, 0.5449396 , 0.347548  ],
       [0.81116724, 0.30386263, 0.13721019]], dtype=float32)

In [65]:
x.add(10)

tensor([[10.9990, 10.2840, 10.7426],
        [10.1356, 10.5449, 10.3475],
        [10.8112, 10.3039, 10.1372]])

In [73]:
import numpy as np
a = np.random.rand(1,5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)

print(a)
print(b)

[[1.68430281 1.67457417 1.17681671 1.57493169 1.09798504]]
tensor([[1.6843, 1.6746, 1.1768, 1.5749, 1.0980]], dtype=torch.float64)


In [75]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x+y
    
    print(z)
    print(z.to("cpu", torch.double))


tensor([[1.9990, 1.2840, 1.7426],
        [1.1356, 1.5449, 1.3475],
        [1.8112, 1.3039, 1.1372]], device='cuda:0')
tensor([[1.9990, 1.2840, 1.7426],
        [1.1356, 1.5449, 1.3475],
        [1.8112, 1.3039, 1.1372]], dtype=torch.float64)
