# Autograd

In [29]:
import torch

x = torch.ones(2, 2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [30]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [31]:
y.grad_fn

In [32]:
z = y*y*3
out = z.mean()

print(z)
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


In [33]:
a = torch.rand(3,3)
a = (2*a)+3
print(a)
print(a.requires_grad)

# change requires_grad in place
a.requires_grad_(True)
print(a)
b = (a*a).sum()
print(b)
print(b.grad_fn)


tensor([[3.1001, 4.3184, 4.5754],
        [3.5336, 3.3831, 4.7765],
        [3.9711, 3.7767, 3.1712]])
False
tensor([[3.1001, 4.3184, 4.5754],
        [3.5336, 3.3831, 4.7765],
        [3.9711, 3.7767, 3.1712]], requires_grad=True)
tensor(136.0296, grad_fn=<SumBackward0>)


## Compute Gradients

In [34]:
print(out)
out.backward()


tensor(27., grad_fn=<MeanBackward0>)


In [35]:
# d(out)/dx
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [49]:
x = torch.randn(3, requires_grad=True)
print(x)

y = x*2
while y.data.norm() < 1000:
    y = y * 2

print(y)


tensor([-1.0822, -0.0789,  0.3765], requires_grad=True)
tensor([-1108.1949,   -80.8005,   385.5107], grad_fn=<MulBackward0>)


In [50]:
# vector-Jacobian product
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)


tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


tensor([1.4348e+00, 1.2653e+03, 6.2848e-02], grad_fn=<MulBackward0>)

In [51]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
